### PR TITLE
Add template option to Idyll create command

### PR DESCRIPTION
**Pull request by codemayank**
* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature update.

* **What is the current behavior?** (You can also link to an open issue here)
Addresses #477 

* **What is the new behavior (if this is a feature change)?**
Adds a ```template``` option to the ```idyll create``` command. For example, ```idyll create -t ../my-blog-post-template``` this would create a project using custom template my-blog-post-template.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

* **Other information**:

### CODE REVIEW

**Comment by mathisonian** [comment]
Thanks for this @codemayank! I'll test and review later today.

**Comment by mathisonian** [comment]
This seems to work great @codemayank, I had no issues with functionality - going to leave a few minor notes in the code.

I think while we're changing the template handling in `idyll create`, this is a good opportunity to think through what's going to happen when there are multiple built-in templates to choose from. (This may also affect how you respond to the code review notes)

I think what we probably want to do (assuming a custom template is not provided by the `--template` flag) is to give the user a choice of templates:

```
? Which template would you like to use
  - templateA
  - templateB
  - Custom (enter path)
```

This would mean un-commenting this code https://github.com/idyll-lang/idyll/blob/master/packages/idyll-cli/bin/cmds/create-project.js#L60-L65, and having it conditionally execute when both (1) no custom template is provided via the command line flag and (2) multiple templates exist in https://github.com/idyll-lang/idyll/tree/master/packages/idyll-template-projects.

**Comment by codemayank** [comment]
@mathisonian I have added the functionality to show the choice of templates when the template flag is not set.

idyll-create

The prompt for templates will be skipped if the template flag is set.

idyll-create-template

**Comment by mathisonian** [comment]
The new functionality looks great - thanks @codemayank! 

I've merged and pushed a few tweaks cleaning things up (https://github.com/idyll-lang/idyll/commit/c81ef129f8d3a20d3bbc96227b240562d1de271d). 

I'll update the release notes and add this to the next published version. Per the project's standards, since you've made a non-trivial contribution, I'll make you a member of the organization. For future PRs you can branch directly off of the main Idyll master instead of using a fork.

**Comment by mathisonian** [comment]
Also, I just realized I left my review in "pending" mode so you may not have seen it - it basically suggested the changes I made in https://github.com/idyll-lang/idyll/commit/c81ef129f8d3a20d3bbc96227b240562d1de271d. Sorry about that

**Pull request merged**
