### PR TITLE
React 16

### PR DESCRIPTION
**Pull request by mathisonian**
This updates the project to use react-16 (targeted against the `idyll-doc-updates` branch). Its a relatively minor change, but will be good to get in, and will potentially allow us to take advantage of the new error boundary features.

There are some warnings being thrown by Victory (only in dev - not production) but they are aware and say they'll fix these in the next release https://github.com/FormidableLabs/victory/issues/724

### CODE REVIEW

**Comment by bclinkinbeard** [comment]
I definitely want to get onto 16 but enzyme doesn't support it yet.

**Comment by mathisonian** [comment]
Ah yeah, looks like we'll need to follow https://github.com/airbnb/enzyme/pull/1007 and https://github.com/airbnb/enzyme/issues/928. Looks like it won't be supported until they release v3

**Comment by bclinkinbeard** [comment]
Updated the other packages and rebased against master. @mathisonian if you're good with this click the button :)

**Comment by mathisonian** [comment]
One of the cli tests is failing with `TypeError: React.createClass is not a function`. It looks like there's a little more cleanup to do to get that working, then I'm good to merge

**Comment by bclinkinbeard** [comment]
Where did you see that particular error? I think I'm only seeing Enzyme-related failures.

Also, why are Travis and Appveyor both running twice?

**Comment by mathisonian** [comment]
In the travis build - it seems like the react-micro-bar-chart doesn't like react 16

```
    console.error src/index.js:102
      TypeError: React.createClass is not a function
          at Object.<anonymous> (/home/travis/build/idyll-lang/idyll/packages/idyll-cli/test/test-project/src/node_modules/react-micro-bar-chart/dist/index.js:10:24)
          at Runtime._execModule (/home/travis/build/idyll-lang/idyll/node_modules/jest-runtime/build/index.js:446:13)
          at Runtime.requireModule (/home/travis/build/idyll-lang/idyll/node_modules/jest-runtime/build/index.js:294:14)
          at Runtime.requireModuleOrMock (/home/travis/build/idyll-lang/idyll/node_modules/jest-runtime/build/index.js:364:19)
          at /home/travis/build/idyll-lang/idyll/packages/idyll-cli/src/pipeline/parse.js:206:29
          at Array.forEach (native)
          at Object.<anonymous>.exports.getHTML (/home/travis/build/idyll-lang/idyll/packages/idyll-cli/src/pipeline/parse.js:204:27)
          at /home/travis/build/idyll-lang/idyll/packages/idyll-cli/src/pipeline/index.js:42:21
          at tryCatcher (/home/travis/build/idyll-lang/idyll/node_modules/bluebird/js/release/util.js:16:23)
...
```

It is their default setting to run twice like that, but we can probably change it to not

**Comment by mathisonian** [comment]
I just tweaked some settings - hopefully they'll only run once for PRs now

**Comment by bclinkinbeard** [comment]
I removed `react-micro-bar-chart`

**Comment by mathisonian** [comment]
I'm still seeing errors, now from `reactable` (looks like it is documented here https://github.com/glittershark/reactable/issues/381 - but that library hasn't been updated in a while). I wonder if its worth trying to patch that, or just finding a better maintained table component. 

I'll take a look at options a little later on today

**Comment by bclinkinbeard** [comment]
https://facebook.github.io/fixed-data-table/ seems legit

**Comment by mathisonian** [comment]
That one is apparently not maintained either? https://github.com/facebook/fixed-data-table/issues/468 

Whats the deal with table libraries? (╯°□°）╯︵ ┻━┻

**Comment by bclinkinbeard** [comment]
Son of a

________________________________

**Comment by mathisonian** [comment]
This one looks like it has potential, and a simple but still powerful API which is a plus

**Pull request closed without merging**
