### PR TITLE
Node 15 react tooltip fix

### PR DESCRIPTION
**Pull request by rogerfitz**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
No tests added but passes tests on node 15

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Upgrades react-tooltip library to fix issue install idyll with node 15.

* **What is the current behavior?** (You can also link to an open issue here)
#693 was patched by removing the dependency here https://github.com/idyll-lang/idyll/pull/705

* **What is the new behavior (if this is a feature change)?**
Adds back the dependency with upgraded version

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
- I updated react-tooltip to higher version. Diff should be much cleaner and I found some unnecessary stuff in my last PR I closed

### CODE REVIEW

**Comment by rogerfitz** [comment]
Still need to fix #680. I can see the error now following https://github.com/idyll-lang/idyll/issues/694#issuecomment-791677608 with node 15 running but not node 14. Happens when I run `idyll` in `my-idyll-post`

**Comment by mathisonian** [comment]
No problem, this looks great - thanks @rogerfitz! I can merge now or wait and review once a fix for #680 is in

**Comment by mathisonian** [comment]
I'm going to go ahead and merge so we can publish a version with this patched https://github.com/idyll-lang/idyll/pull/707/files#diff-7992088eddfefcd56354965a72d75010b7c7aad4dabaff28a54b378a479ed3ffR15-R17

**Comment by rogerfitz** [comment]
@mathisonian Sounds good RE the merge. Little busier this week but should have some time to fix #680 I'll keep you posted

**Pull request merged**
