### PR TITLE
Check in test project deps

### PR DESCRIPTION
**Pull request by bclinkinbeard**
Test project build artifacts *will* be ignored now, since they should be generated fresh every time the tests run. Artifacts will also be cleared at the beginning of each test run.

### CODE REVIEW

**Comment by mathisonian** [comment]
Cool, this means we can remove the custom windows test script as well

**Comment by bclinkinbeard** [comment]
Oh cool, I can push up a commit for that. I am again mystified that Travis builds are failing though.

**Comment by bclinkinbeard** [comment]
What just happened lol

**Comment by mathisonian** [comment]
I updated the CI scripts to use yarn, I think that + `node_modules` should fix the build

**Pull request merged**
