### PR TITLE
Add annotation component

### PR DESCRIPTION
**Pull request by jasenlo123**
* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This introduces an Annotation component in Idyll's built-in component package.
Notes and examples [here](https://idyll.pub/post/test-add-annotation-856c8e2d73defca8e72c791e/)

* **What is the current behavior?** (You can also link to an open issue here)
N/A. It's a new feature.

* **What is the new behavior (if this is a feature change)?**
N/A. It's a new feature.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
This PR should have no breaking changes, doesn't interact with any other components or have any dependencies.

* **Other information**:
Currently fails tests that I added into `idyll-componenets/tests/components.js` and not sure why. Other notes, issues and conncerns [here](https://idyll.pub/post/test-add-annotation-856c8e2d73defca8e72c791e/).

### CODE REVIEW

**Comment by mathisonian** [comment]
Thanks @jasenlo123! 

It will be great to have this component added to the library - it seems super useful. For the PR, a few things to tidy it up a bit before we merge: 

- could you revert the changes to `PULL_REQUEST_TEMPLATE.md` this is the file that generates the prompts for people to fill out when submitting a PR like this. It seems like you edited that file with info on this specific PR
- could you remove the top level `test-add-annotation` folder that was added, we'd like to keep all the tests for components in `packages/idyll-components/test/` if possible

**Comment by mathisonian** [comment]
Regarding the failing tests I believe you'll just need to add your component to the export here: https://github.com/idyll-lang/idyll/blob/master/packages/idyll-components/src/index.js @jasenlo123

**Review by mathisonian — CHANGES_REQUESTED** [review]
Noted a few change requests above

**Comment by jasenlo123** [comment]
helu @mathisonian !

Thanks for the review. And ops. I'll make the amendments.

One thing, just to clarify that the `test-add-annotation` is doesn't contain tests per say, it's the Idyll project I created to test out the feature. I opted to keep it in because I wasn't sure if I should or where to put the `CSS` that enables the annotation functionality. Thus, the relevant `CSS` is in the `styles.css` inside `test-add-annotation`. 

Would you mind advising where to place the `CSS` -  Is it `idyll-themes` or `idyll-template-projects`?

**Comment by mathisonian** [comment]
Ahh understood. In that case I think it makes the most sense to add this CSS to the themes. These aren't super modular yet so you'll have to repeat it for each theme. You can add to the bottom of each of these files to update: 

- https://github.com/idyll-lang/idyll/blob/master/packages/idyll-themes/src/default/styles.js#L1008
- https://github.com/idyll-lang/idyll/blob/master/packages/idyll-themes/src/github/styles.js
- https://github.com/idyll-lang/idyll/blob/master/packages/idyll-themes/src/idyll/styles.js
- https://github.com/idyll-lang/idyll/blob/master/packages/idyll-themes/src/tufte/styles.js

**Review by mathisonian — APPROVED** [review]

**Comment by mathisonian** [comment]
This looks good to me. I'm just going to test out locally and may suggest a few style tweaks - reading over your [notes](https://idyll.pub/post/test-add-annotation-856c8e2d73defca8e72c791e/) I think it makes sense we can give a more neutral default style and let people add their own CSS to customize. 

Will comment with any updates, then we can merge.

**Comment by mathisonian** [comment]
Just merged with some style tweaks to make the default styles a bit more subtle so people can customize them to match their specific themes more easily. This is available on npm `v5.5.0` and the docs are being re-built now.

**Comment by mathisonian** [comment]
Thanks again @jasenlo123 - since you've made a substantial contribution I've invited you to join as a member of the org, as per our policy. This will make it easier to collaborate on future PRs since you can branch directly off of the `idyll-lang/idyll` master without needing to make forks and also gives you more permissions in managing issues and PRs.

**Comment by jasenlo123** [comment]
Thanks @mathisonian for the invitation and for the quick deployment into production!

I was going to offer to work on the docs but it looks like you already figured it out.

I'm glad to be part of this community, and am looking forward to contributing more to Idyll.

Cheers!

**Pull request merged**
