### PR TITLE
Use findup-sync to reliably find internal dependencies

### PR DESCRIPTION
**Pull request by bclinkinbeard**
Alternative to #72, I just knew there had to be a package out there that solves this problem.

### CODE REVIEW

**Comment by mathisonian** [comment]
Happy to use this lib, but this is failing for me if I run `npm link` in the idyll project directory (for me `~/projects/idyll/`) and then run `idyll test.idl` on a different path (in this case `~/projects/test.idl`)

**Comment by bclinkinbeard** [comment]
Hmm, that scenario works for me. What is the error you're getting?

**Comment by mathisonian** [comment]
```sh
mathisonian in ~/projects
👉 idyll test.idl


Spellcheck:
No misspellings found.
TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at exports.getComponentsJS (/Users/mathisonian/projects/idyll/idyll/src/pipeline/parse.js:39:29)
    at Promise.try (/Users/mathisonian/projects/idyll/idyll/src/pipeline/index.js:31:21)
    at tryCatcher (/Users/mathisonian/projects/idyll/idyll/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/mathisonian/projects/idyll/idyll/node_modules/bluebird/js/release/method.js:39:29)
    at Object.build (/Users/mathisonian/projects/idyll/idyll/src/pipeline/index.js:24:21)
    at IdyllInstance.build (/Users/mathisonian/projects/idyll/idyll/src/index.js:65:16)
    at Object.<anonymous> (/Users/mathisonian/projects/idyll/idyll/bin/idyll.js:78:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```


The default component path is undefined after the path building process so its giving this error. When you run locally under these conditions, what value do you end up with for `DEFAULT_COMPONENTS_DIR`?

**Comment by bclinkinbeard** [comment]
@mathisonian I just pushed a new commit to use native Node dependency finding instead of `findup`.

If I run `idyll test.idl` from the directory above the `idyll` project, `DEFAULT_COMPONENTS_DIR` resolves to `/absolute_path/idyll/node_modules/idyll-default-components`

**Comment by mathisonian** [comment]
That approach feels better, and everything seems to be working correctly on my end. Thanks for the fixes!

**Pull request merged**
