### PR TITLE
Strings have to be wrapped in quotes

### PR DESCRIPTION
**Pull request by bclinkinbeard**
Else things go boom when the expressions are evaluated

### CODE REVIEW

**Comment by mathisonian** [comment]
Before we were doing `JSON.stringify()` for all the values (which takes care of wrapping strings in quotes). Do we need to add logic here for `Obects` as well, or is that handled elsewhere?   https://github.com/idyll-lang/idyll-interactive-document/blob/master/src/visitors/node.js#L93

**Comment by bclinkinbeard** [comment]
Ah OK, I remembering wondering about that. Makes sense now. :) Will update.

**Comment by bclinkinbeard** [comment]
There we go.

**Comment by mathisonian** [comment]
👍 LGTM

**Pull request merged**
