### PR TITLE
feat : incorporate desmos component

### PR DESCRIPTION
**Pull request by amitbadala**
* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Add **Desmos** component

* **What is the current behavior?** (You can also link to an open issue here)
Addresses #357 

* **What is the new behavior (if this is a feature change)?**
User can embed _**Desmos**_ graph into idyll document

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Comment by amitbadala** [comment]
Users can now embed **desmos** graph's within their **idyll** projects
for eg :
```[Desmos apiKey:"dcb31709b452b1cf9dc26972add0fda6" equation:"y=x^2" id:"linear graph"/]```
will embed the respective graph in your document .

desmos

**Comment by amitbadala** [comment]
@mathisonian  what do you think ?

**Comment by mathisonian** [comment]
Sick! A couple quick things:

- Can we drop the `id` requirement, and autogenerate a _unique_ id if one isn't provided. 
- Any way to make this responsive if no width is provided? I imagine this might be tricky if Desmos doesn't have built-in support for it, so okay if the answer is no
- What happens if the equation passed in is a reactive expression? e.g. what if I did something like this? Does the Desmos component respond?

```
[var name:"equation" value:"y = x^2" /]

[Desmos apiKey:"..." equation:equation id:"linear graph"/]

[Button onClick:`equation = "y = x^3" `] Change Equation [/Button]
```

**Comment by amitbadala** [comment]
> 1. Can we drop the `id` requirement, and autogenerate a _unique_ id if one isn't provided.
  **Ans : added autogenerated unique id to the component,but getting this error**
```Prop 'id' did not match. Server: "X" Client: "Y"``` **,so wip** 

> 2. Any way to make this responsive if no width is provided? I imagine this might be tricky if Desmos doesn't have built-in support for it, so okay if the answer is no
   **Ans : width is an optional element if the user doesn't provide it will take the width of the parent element, and automatically become responsive.Yes they have a built-in support.
So it is recommended to avoid width although the option should be available** 

> 3. What happens if the equation passed in is a reactive expression? e.g. what if I did something like this? Does the Desmos component respond? 
  **Ans : added this functionality will be committing the same soon.**

**Comment by mathisonian** [comment]
Thanks @amitbadala!

That all sounds good. And I wasn't meaning to rush you with the review comment, just wanted to make sure you saw the earlier note. 

>  Ans : added autogenerated unique id to the component,but getting this error
Prop 'id' did not match. Server: "X" Client: "Y" ,so wip

This error looks related to server side rendering. I'd check to see if maybe the server is using the non-transpiled version of the component to do the initial render, and the client is using an (outdated) transpiled version. If you need to continually build a component while developing, you can run leave `yarn dev running` inside the `idyll-components` package to automatically recompile on changes.

**Comment by amitbadala** [comment]
@mathisonian  I had seen your reviews and started working on it immediately on all the points including 3rd one should've acknowledged it first.
Regarding this error, I am generating unique id in ```componentWillMount``` lifecycle method and after logging the id. It seems it's executing twice, after executing Idyll command you could see one log in Terminal and another in dev tools. As a result demos component unable to locate the id since it references the previous id

**Comment by mathisonian** [comment]
Ah I see. - yes you'll need to figure out a way so that the IDs are generated in a stable order so things stay consistent across server&client.

**Comment by mathisonian** [comment]
I'd recommend creating an ID in the constructor that references a global counter, and increments it each time a new component is instantiated.

**Comment by amitbadala** [comment]
**Equation passed in reactive expressions**

We have two options to load reactive expression in desmos graph.
1. Clear the existing graph and bind a new graph with the new expression.
2. Add the new equation to the existing graph as shown below where the viewer can have control 

Equations
-----------------------------------------------------------------------------------------------------------------------------------------
**Responsiveness** 
 
responsiveDesmos gif
----------------------------------------------------------------------------------------------------------------------------------------
**Autogenerated unique Id** 

autoIdDesmos

**Comment by amitbadala** [comment]
**Questions**

What if the user doesn't have an API key for desmos?
- Can we provide default apiKey?

**Comment by mathisonian** [comment]
Let's go with option (1) for now. It would be ideal if there was a way for us to capture changes if a user edits the equation directly in the component and push that back to the idyll `equation` prop, but I think for the initial version that's not a requirement.

**Comment by mathisonian** [comment]
The other updates look great! 🎉

**Comment by amitbadala** [comment]
Graph re-render on equation change.

desmosEquation

**Comment by amitbadala** [comment]
**Questions** 

1. What if the user doesn't have an API key? we can add a default API key
2. Currently, the desmos API url is embedded in the code. Where can I abstract it?

**Comment by mathisonian** [comment]
> What if the user doesn't have an API key? we can add a default API key

from https://www.desmos.com/api/v1.3/docs/index.html#document-api-keys:
> The demonstration API key, dcb31709b452b1cf9dc26972add0fda6, is provided for use during development. If you plan to use the API in production, you should contact us by e-mailing info@desmos.com to obtain your own API key.

Maybe we should use that one if no API key is provided? We could also print a warning to the console if they are using the default one (if we do show a warning I think it should probably not show if `NODE_ENV` is `production`).

> Currently, the desmos API url is embedded in the code. Where can I abstract it?

Making constant variables at the top of the file should work

**Comment by amitbadala** [comment]
> if we do show a warning I think it should probably not show when building for production

How can we ensure whether it's building for production?

**Comment by amitbadala** [comment]
> if we do show a warning I think it should probably not show when building for production
how can we track that ?

**Comment by amitbadala** [comment]
> if we do show a warning I think it should probably not show when building for production

how can we track that? Need help !

**Comment by mathisonian** [comment]
I guess the easiest way is to just print on the command line and not the JavaScript console. So move the error check from `componentDidMount` to `constructor` (since the mount event never fires on the server). 

Then use `typeof window === 'undefined'` to check if the code is running under node.js rather than in a web browser.

**Comment by amitbadala** [comment]
@mathisonian  done !!

**Comment by mathisonian** [comment]
The updates look great @amitbadala. I just pushed a few minor edits along with code to support communication from the Desmos component back to Idyll. See attached GIF. 

I think its ready to go after these tests pass. Any other updates you wanted to make? 
desmos --  idyll

**Comment by amitbadala** [comment]
>Any other updates you wanted to make?

I think this is good for the basic version, for now, let's see what users think of it and we can work on their feedback accordingly.

**Pull request merged**
