### PR TITLE
add param case

### PR DESCRIPTION
**Pull request by mathisonian**
Re: https://github.com/idyll-lang/idyll/issues/152, I'm trying to make sure things work out of the box with the CLI and the new `IdyllDocument`. This has made one change so far:

1. Add another lookup case of component names to ensure the component map passed from the CLI works correctly.

### CODE REVIEW

**Comment by bclinkinbeard** [comment]
Do we really need to worry about Node 6? Current version is 8.4.

We're also using `Object.entries` in a couple places which has the same support. I vote for a "current plus previous major" approach.

**Comment by mathisonian** [comment]
I'd prefer to go at least 2 back since it is user facing, and in my experience a lot of people are slow to upgrade or just use the even-numbered LTS versions. 

I don't mind doing the PRs to fix any existing issues

**Comment by bclinkinbeard** [comment]
Can we put the changes in their own PR and https://www.npmjs.com/package/object.values and https://www.npmjs.com/package/object.entries? That way we can just remove the shims at some point in the future.

**Comment by mathisonian** [comment]
Okay, I've reverted those changes here and opened https://github.com/idyll-lang/idyll/pull/156 with the shims

**Pull request merged**
