### PR TITLE
docs: Separate pages for tutorials and example gallery

### PR DESCRIPTION
**Pull request by a-nozeret**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Docs update / feature: Separate pages for tutorials and example gallery.

* **What is the current behavior?** (You can also link to an open issue here)
Resolve issue #516 

* **What is the new behavior (if this is a feature change)?**
Idyll Tutorials

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
/

* **Other information**:
/

**Note:** @mathisonian let me know if the order of tabs navigation should change or whether some text is needed before the gallery section.

### CODE REVIEW

**Comment by mathisonian** [comment]
Awesome! Thanks for this @a-nozeret. 

I'll test locally and respond to your note above shortly

**Comment by mathisonian** [comment]
This looks great - thanks again @a-nozeret! 

I may add some text and additional structure to the tutorials page, but its already a big improvement. Merging and will deploy to idyll-lang.org in a minute.

**Comment by mathisonian** [comment]
Per our policy, since you've made a substantive PR, I've sent you an invite to join the Idyll organization. This gives you the ability to submit PRs branched directly off of this repo instead of forking, which can make collaborating easier, and enables some additional privileges on issues, etc.

**Comment by a-nozeret** [comment]
great! thank you @mathisonian

**Pull request merged**
